# Lab Session 4

**Student Name:** Chevula Mahendra  
**Student ID:** 0625602  
**University:** Golden Gate University  

---

## Lab Topic
*Lab4_Pandas / Lab 4 Concepts*

In [1]:
import pandas as pd
import numpy as np

## Create Sample DataFrame

In [2]:
data = {
    'Student': ['A', 'B', 'C', 'D', 'E'],
    'Math': [78, 85, 96, 67, 88],
    'Science': [90, 89, 94, 70, 85],
    'English': [85, 78, 88, 72, 90]
}

df = pd.DataFrame(data)
df

  Student  Math  Science  English
0       A    78       90       85
1       B    85       89       78
2       C    96       94       88
3       D    67       70       72
4       E    88       85       90

## Dataset Information

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      object
 1   Math     5 non-null      int64
 2   Science  5 non-null      int64
 3   English  5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

## Statistical Summary

In [4]:
df.describe()

           Math    Science   English
count   5.00000   5.000000   5.00000
mean   82.80000  85.600000  82.60000
std    10.94075   9.289779   7.46994
min    67.00000  70.000000  72.00000
25%    78.00000  85.000000  78.00000
50%    85.00000  89.000000  85.00000
75%    88.00000  90.000000  88.00000
max    96.00000  94.000000  90.00000

## Calculate Average Marks

In [5]:
df['Average'] = df[['Math','Science','English']].mean(axis=1)
df

  Student  Math  Science  English    Average
0       A    78       90       85  84.333333
1       B    85       89       78  84.000000
2       C    96       94       88  92.666667
3       D    67       70       72  69.666667
4       E    88       85       90  87.666667

## Sort Students by Average Score

In [6]:
df.sort_values(by='Average', ascending=False)

  Student  Math  Science  English    Average
2       C    96       94       88  92.666667
4       E    88       85       90  87.666667
0       A    78       90       85  84.333333
1       B    85       89       78  84.000000
3       D    67       70       72  69.666667